try {
   int d = 0;
   double catchedRes1 = intArray[8] / d;
   System.out.println("catchedRes1 = " + catchedRes1);
} catch (ArithmeticException e) {
   System.out.println("Catching exception: " + e);
}
Исправленный код
try {
   int d = 0;
   double catchedRes1;
   if (d != 0) {
       catchedRes1 = intArray[8] / d;
       System.out.println("catchedRes1 = " + catchedRes1);
   } else {
       System.out.println("Ошибка: деление на ноль!");
   }
} catch (ArithmeticException e) {
   System.out.println("Catching exception: " + e);
}